### ISSUE TITLE
Slicing anndata removes unused categories

### ISSUE THREAD

**Issue by sjfleming** [scverse/anndata#1710] opened 2024-10-11 19:41 UTC
### Please make sure these conditions are met

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Code:

```python
import anndata
import numpy as np
import pandas as pd

# dummy anndata with two cells and the "batch" annotations [0, 1]
adata = anndata.AnnData(X=np.zeros((2, 1)), obs=pd.DataFrame(data={'batch': [0, 1]}))
adata.obs['batch'] = adata.obs['batch'].astype('category')

print('initial categories')
print(adata.obs['batch'].cat.categories)

# slice the anndata: the categorical categories change
print('categories after slicing (view)')
print(adata[[0]].obs['batch'].cat.categories)
print('categories after slicing (copy)')
print(adata[[0]].copy().obs['batch'].cat.categories)
```

stdout:

```
initial categories
Index([0, 1], dtype='int64')
categories after slicing (view)
Index([0], dtype='int64')
categories after slicing (copy)
Index([0], dtype='int64')
```

Traceback:

There is no actual error raised.

Comment:

This behavior was unexpected to me.  I would have naively expected the categorical categories in `obs` to be preserved with slicing an `AnnData`.

My use case is that I want to iterate over a large `AnnData` and write it to files in chunks.  But when I do this, I get categorical variables in `obs` whose categories no longer match.

### Versions

-----
anndata             0.10.9
session_info        1.0.0
-----
cython_runtime      NA
dateutil            2.9.0
exceptiongroup      1.2.0
h5py                3.10.0
natsort             8.4.0
numpy               1.26.4
packaging           24.0
pandas              2.2.1
pytz                2024.1
scipy               1.12.0
six                 1.16.0
sphinxcontrib       NA
torch               2.2.1
torchgen            NA
tqdm                4.66.2
typing_extensions   NA
zoneinfo            NA
-----
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
macOS-14.1-arm64-arm-64bit
-----
Session information updated at 2024-10-11 15:40

**Comment by flying-sheep** [comment] 2024-10-12 15:02
Fixed in #1340, see https://anndata.readthedocs.io/en/latest/release-notes/index.html#rc1-2024-09-04

**Comment by flying-sheep** [comment] 2024-10-12 15:03
Duplicate of https://github.com/scverse/anndata/issues/890

**Closed by flying-sheep** 2024-10-12 15:02 UTC
Labels: Bug 🐛, Triage 🩺

**Comment by sjfleming** [comment] 2024-10-12 20:09
Thanks @flying-sheep , sorry I’m not sure how I missed those when I was searching
