### ISSUE TITLE
H5ad converts string/object to categorical when saving and reading

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/anndata#1607] opened 2024-08-23 08:54 UTC
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report
Hi,
My anndata.obs has a column of dtype object(string), but when I saved the h5ad and read again with scanpy, the column became categorical ! Then it made conflicts with my spatialdata objects.
```
adata.write("adata.h5ad")
sc.read_h5ad("adata.h5ad")
```

### Versions

```python

the anndata version: 0.10.8
the scanpy version: 1.10.2
```

**Comment by wangjiawen2013** [comment] 2024-08-23 08:58
![image](https://github.com/user-attachments/assets/bcde0feb-1d7d-4006-8fb4-3b47a8e4da69)

![image](https://github.com/user-attachments/assets/1776f3e2-4a90-4ea4-b30d-043026781e7e)

**Comment by flying-sheep** [comment] 2024-08-23 09:14
Duplicate of #534, please subscribe to that issue

**Closed by flying-sheep** 2024-08-23 09:14 UTC
Labels: Bug 🐛, Triage 🩺

**Comment by wangjiawen2013** [comment] 2024-11-28 07:37
@flying-sheep 
There is still no parameter `convert_strings_to_categoricals` in the function `write_h5ad` though it has already in the main branch and the released note. I tried v0.11.0 and 0.11.1. There is no `convert_strings_to_categoricals`
![Image](https://github.com/user-attachments/assets/46af9cd8-8874-476e-bc95-f941de9016af)

**Comment by wangjiawen2013** [comment] 2025-02-12 03:31
I find the reason, Scanpy doesn't make changes to be compatible with the anndata, so we cannot use `strings_to_categoricals ` in scanpy.
