### ISSUE TITLE
Set of categories changes when slicing AnnData, but not when slicing DataFrame

### ISSUE THREAD

**Issue by jacksonloper** [scverse/anndata#1526] opened 2024-06-13 18:50 UTC
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Every time you slice an AnnData, the pd.Categorical objects get reconstructed (potentially with a new set of categories).  Pandas has the opposite behavior (set of categories stays the same, even if it includes categories that are no longer represented).  Example below.

Probably either this should be (a) changed or (b) better documented.  Just got bit by this and took a long time to figure out my bug :).  

```python

import anndata
import pandas as pd

ad=anndata.AnnData(
    obs=pd.DataFrame(data=dict(animal=pd.Categorical(['cat','dog','dog'])))
)
print(ad.obs.animal.cat.categories)
print(ad[1:].obs.animal.cat.categories)
print(ad.obs.iloc[1:].animal.cat.categories)

```

Results:

```pytb
Index(['cat', 'dog'], dtype='object')
Index(['dog'], dtype='object')
Index(['cat', 'dog'], dtype='object')
```

### Versions

```python
-----
anndata             0.10.7
pandas              2.2.2
session_info        1.0.0
-----
anyio                       NA
apport_python_hook          NA
argcomplete                 NA
arrow                       1.3.0
astunparse                  1.6.3
attr                        23.1.0
attrs                       23.1.0
babel                       2.13.1
backcall                    0.2.0
bottleneck                  1.3.2
brotli                      1.0.9
certifi                     2020.06.20
chardet                     4.0.0
charset_normalizer          3.3.2
cloudpickle                 2.0.0
colorama                    0.4.4
cython_runtime              NA
dask                        2022.01.0+dfsg
dateutil                    2.8.2
debugpy                     1.8.0
decorator                   4.4.2
exceptiongroup              1.2.0
fastjsonschema              NA
fqdn                        NA
fsspec                      2023.12.1
gi                          3.42.1
gio                         NA
glib                        NA
gobject                     NA
google                      NA
gtk                         NA
h5py                        3.6.0
idna                        3.3
ipykernel                   6.7.0
isoduration                 NA
jedi                        0.18.0
jinja2                      3.0.3
json5                       NA
jsonpointer                 2.4
jsonschema                  4.20.0
jsonschema_specifications   NA
jupyter_events              0.9.0
jupyter_server              2.12.1
jupyterlab_server           2.25.2
lz4                         3.1.3+dfsg
markupsafe                  2.0.1
mpl_toolkits                NA
natsort                     8.4.0
nbformat                    5.9.2
netifaces                   0.11.0
numexpr                     2.8.8
numpy                       1.25.2
overrides                   NA
packaging                   21.3
parso                       0.8.1
pexpect                     4.8.0
pickleshare                 0.7.5
platformdirs                4.1.0
prometheus_client           NA
prompt_toolkit              3.0.28
psutil                      5.9.6
ptyprocess                  0.7.0
pyarrow                     14.0.2
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.9.5
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.17.2
pynvml                      NA
pythonjsonlogger            NA
pytz                        2022.1
referencing                 NA
requests                    2.31.0
rfc3339_validator           0.1.4
rfc3986_validator           0.1.1
rpds                        NA
scipy                       1.13.0
send2trash                  NA
setuptools                  69.0.2
simplejson                  3.17.6
sitecustomize               NA
six                         1.16.0
sniffio                     1.3.0
storemagic                  NA
tblib                       1.7.0
tlz                         0.12.1
toolz                       0.12.1
torch                       2.3.1+cu121
torchgen                    NA
tornado                     6.4
tqdm                        4.66.1
traitlets                   5.14.0
typing_extensions           NA
tzdata                      2024.1
uri_template                NA
urllib3                     1.26.5
wcwidth                     0.2.5
webcolors                   1.13
websocket                   1.7.0
yaml                        5.4.1
zmq                         25.1.2
zoneinfo                    NA
-----
IPython             7.31.1
jupyter_client      8.6.0
jupyter_core        5.5.0
jupyterlab          4.0.9
notebook            7.0.6
-----
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Linux-5.15.0-105-generic-x86_64-with-glibc2.35
-----
Session information updated at 2024-06-13 14:48
```

**Comment by flying-sheep** [comment] 2024-06-17 14:14
Please check the existing issues before opening new ones. This is a duplicate of #890, which was recently closed.

It was closed in #1340 which will appear in 0.11.0

**Closed by flying-sheep** 2024-06-17 14:14 UTC
Labels: Bug 🐛, Triage 🩺
